[package]
name = "photo-archive"
version = "0.1.0"
authors = ["Fabian Thorand <f.thorand@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
walkdir = "2.2.7"
rusqlite = "0.16.0"

cairo-rs = "0.5.0"
gdk = "0.9.0"
glib = "0.6.1"
gtk = "0.5.0"
gio = "0.5.1"

kamadak-exif = "0.3.1"

log = "0.4.6"
env_logger = "0.6.0"

[features]
default = ["gtk/v3_10"]
